# Generated by Django 4.1.5 on 2023-02-19 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EhubSl', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='email',
            field=models.EmailField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='msg',
            field=models.TextField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='subject',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='username',
            field=models.TextField(max_length=50, null=True),
        ),
    ]
